on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

name: Deploy mdBook site to Pages

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.36
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.6.9

      - name: Install dependencies
        run: |
          cargo binstall --no-confirm --version ${MDBOOK_VERSION} mdbook
          cargo binstall --no-confirm mdbook-linkcheck

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with mdBook (Main)
        run: |
          make all

      # TODO: Condition compile docs on certain inputs
      # - uses: actions/checkout@v4
      #   with:
      #     repository: "epi-project/brane"
      #     path: code
      #
      # - name: Build code documentation
      #   run: |
      #     cd code
      #     cargo doc --workspace
      #     cp -r target/doc ../build/docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
          name: docs-${{ inputs.ref }}
